test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -59,7 +59,7 @@ jobs:
 
       - name: Extract tag name
         id: get_tag
-        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
+        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
 
       - name: Build Docker image
         run: |
@@ -78,56 +78,57 @@ jobs:
     needs: [build, check_secrets]
 
     steps:
-    - name: SSH to server and deploy
-      uses: appleboy/ssh-action@v0.1.5
-      with:
-        host: ${{ secrets.SERVER_IP }}
-        username: matejv
-        key: ${{ secrets.SSH_PRIVATE_KEY }}
-        script: |
-          # Debugging the GITHUB_REF value
-          echo "GITHUB_REF=${{ github.ref }}"
-          
-          # If GITHUB_REF is set, extract TAG_NAME
-          if [ -n "${{ github.ref }}" ]; then
-            TAG_NAME="${{ github.ref#refs/tags/ }}"
-          else
-            echo "Error: GITHUB_REF is not set"
-            exit 1
-          fi
+      - name: SSH to server and deploy
+        uses: appleboy/ssh-action@v0.1.5
+        with:
+          host: ${{ secrets.SERVER_IP }}
+          username: matejv
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          script: |
+            # Debugging the GITHUB_REF value
+            echo "GITHUB_REF=${{ github.ref }}"
 
-          echo "TAG_NAME=${TAG_NAME}"
+            # If GITHUB_REF is set, extract TAG_NAME
+            if [ -n "${{ github.ref }}" ]; then
+              TAG_NAME="${{ github.ref }}" 
+              TAG_NAME="${TAG_NAME##*/}"  # Extract the tag name
+            else
+              echo "Error: GITHUB_REF is not set"
+              exit 1
+            fi
 
-          # Construct the Docker image name
-          IMAGE_NAME="${{ secrets.DOCKER_REPO }}/${{ github.repository }}:${TAG_NAME}"
-          CONTAINER_NAME="$(basename "${{ github.repository }}")"
-          EXPOSED_PORT="${{ secrets.EXPOSED_PORT }}"
-          INTERNAL_PORT="${{ secrets.INTERNAL_PORT }}"
+            echo "TAG_NAME=${TAG_NAME}"
 
-          # Print the Docker image being pulled
-          echo "Pulling Docker image: $IMAGE_NAME"
-          docker pull "${IMAGE_NAME}"
+            # Construct the Docker image name
+            IMAGE_NAME="${{ secrets.DOCKER_REPO }}/${{ github.repository }}:${TAG_NAME}"
+            CONTAINER_NAME="$(basename "${{ github.repository }}")"
+            EXPOSED_PORT="${{ secrets.EXPOSED_PORT }}"
+            INTERNAL_PORT="${{ secrets.INTERNAL_PORT }}"
 
-          # Check if the container already exists
-          echo "Checking if container $CONTAINER_NAME exists..."
-          if [ "$(docker ps -aq -f name=^${CONTAINER_NAME}$)" ]; then
-            echo "Stopping and removing existing container..."
-            docker stop "$CONTAINER_NAME"
-            docker rm "$CONTAINER_NAME"
-          else
-            echo "No existing container found. Skipping stop and remove."
-          fi
+            # Print the Docker image being pulled
+            echo "Pulling Docker image: $IMAGE_NAME"
+            docker pull "${IMAGE_NAME}"
 
-          # Extract and set environment variables for the container
-          echo "Extracting APP_ environment variables..."
-          ENV_VARS=$(printenv | grep '^APP_' | awk '{print "-e " $1}')
+            # Check if the container already exists
+            echo "Checking if container $CONTAINER_NAME exists..."
+            if [ "$(docker ps -aq -f name=^${CONTAINER_NAME}$)" ]; then
+              echo "Stopping and removing existing container..."
+              docker stop "$CONTAINER_NAME"
+              docker rm "$CONTAINER_NAME"
+            else
+              echo "No existing container found. Skipping stop and remove."
+            fi
 
-          # Run the new container
-          echo "Running new container..."
-          docker run -d \
-            --restart unless-stopped \
-            -p "$EXPOSED_PORT:$INTERNAL_PORT" \
-            --name "$CONTAINER_NAME" \
-            $ENV_VARS \
-            "${IMAGE_NAME}"
+            # Extract and set environment variables for the container
+            echo "Extracting APP_ environment variables..."
+            ENV_VARS=$(printenv | grep '^APP_' | awk '{print "-e " $1}')
+
+            # Run the new container
+            echo "Running new container..."
+            docker run -d \
+              --restart unless-stopped \
+              -p "$EXPOSED_PORT:$INTERNAL_PORT" \
+              --name "$CONTAINER_NAME" \
+              $ENV_VARS \
+              "${IMAGE_NAME}"
 
