test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -85,15 +85,30 @@ jobs:
         username: matejv
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         script: |
-          TAG_NAME="${{ env.TAG_NAME }}"  # Using the environment variable from earlier
+          # Debugging the GITHUB_REF value
+          echo "GITHUB_REF=${GITHUB_REF}"
+          
+          # If GITHUB_REF is set, extract TAG_NAME
+          if [ -n "${GITHUB_REF}" ]; then
+            TAG_NAME="${GITHUB_REF#refs/tags/}"
+          else
+            echo "Error: GITHUB_REF is not set"
+            exit 1
+          fi
+          
+          echo "TAG_NAME=${TAG_NAME}"
+          
+          # Construct the Docker image name
           IMAGE_NAME="${{ secrets.DOCKER_REPO }}/${{ github.event.repository.name }}:${TAG_NAME}"
           CONTAINER_NAME="$(basename "${{ github.event.repository.name }}")"
           EXPOSED_PORT="${{ secrets.EXPOSED_PORT }}"
           INTERNAL_PORT="${{ secrets.INTERNAL_PORT }}"
 
+          # Print the Docker image being pulled
           echo "Pulling Docker image: $IMAGE_NAME"
           docker pull "${IMAGE_NAME}"
 
+          # Check if the container already exists
           echo "Checking if container $CONTAINER_NAME exists..."
           if [ "$(docker ps -aq -f name=^${CONTAINER_NAME}$)" ]; then
             echo "Stopping and removing existing container..."
@@ -103,9 +118,11 @@ jobs:
             echo "No existing container found. Skipping stop and remove."
           fi
 
+          # Extract and set environment variables for the container
           echo "Extracting APP_ environment variables..."
           ENV_VARS=$(printenv | grep '^APP_' | awk '{print "-e " $1}')
 
+          # Run the new container
           echo "Running new container..."
           docker run -d \
             --restart unless-stopped \
